### ISSUE TITLE
Remove Vagrant from release message

### ISSUE THREAD

**Issue by solairen** [solairen/docker_vagrant#4]
**Describe the solution you'd like**</br>
When a release is created the message contains ``Vagrant``. It is obsolete due to the changed output message.

```yaml
 - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ steps.current-time.outputs.formattedTime }}
        body: |
          Changes in this release:
            - Vagrant ${{ needs.Check_Version.outputs.ver }}
        draft: false
        prerelease: false
```
